# .cargo/audit.toml
[advisories]
ignore = [
    "RUSTSEC-2026-0098",  # rustls-webpki: URI name constraints incorrectly accepted
    "RUSTSEC-2026-0099",  # rustls-webpki: wildcard name constraints
    "RUSTSEC-2026-0104",  # rustls-webpki: reachable panic in CRL parsing
]
